import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import React from "react";
import {Props, Posts} from "../types/types"
import fs from "fs";
import matter from "gray-matter"

const Home: NextPage<Props> = ({posts}:Props) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className={styles.title}>
          블로그 <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Image src={'/pikaa.webp'} alt="" width={400} height={400} />
        {posts.map(({ slug, frontmatter }) => (
        <div
          key={slug}
          className=""
        >
          <Link href={`/${slug}`}>
            <a>
              <h1>{frontmatter.title}</h1>
            </a>
          </Link>
        </div>
      ))}

    </div>
  )
}

export default Home





export async function getStaticProps() {

  const files = fs.readdirSync('__posts');

  const posts: Posts[] = files.map((fileName) => {
    const slug = fileName.replace('.md', '');
    const readFile = fs.readFileSync(`__posts/${fileName}`, 'utf-8');
    const { data: frontmatter } = matter(readFile);

    return {
      slug,
      frontmatter,
    };
  });

  return {
    props: {
      posts,
    },
  };
}

